services:
  turnierplaner:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
      network: host
    container_name: turnierplaner
    ports:
      - "8000:80"
    volumes:
      - ../data:/var/www/html/data
    devices:
      - "/dev/snd:/dev/snd"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCKER_BUILDKIT=0

