# erstellen eines Linux executables: 
#    cd /mnt/c/temp/VSV && /mnt/c/temp/VSV/.venv/bin/pyinstaller --onefile --windowed --icon=countdown.ico countdown.py 2>&1 | tail -20
# ausführen in der console von wsl
#    sudo apt install python3-pygame
#    cd /mnt/c/temp/VSV/ && .venv/bin/python3 countdown.py

# fuer windows unter windows folgendes tun:
#    Installiere Python für Windows:
#        Download von https://www.python.org/downloads/
#        Wichtig: Aktiviere "Add Python to PATH" während der Installation
#    cd C:\temp\VSV
#    python -m venv venv
#    venv\Scripts\activate
#    pip install pygame pyinstaller
#    pyinstaller --onefile --windowed countdown.py
# Music konvertieren
#    ffmpeg -i sounds/Music/infile.m4a -c:v copy -c:a libmp3lame -q:a 4 sounds/Music/outfile.mp3

[timer]
# Startwert des Countdowns
# Entweder als Sekunden (z.B. 300) ODER im Format MM:SS (z.B. 05:00)
start = 10:01

# Startalarm als Sekunden vor Zeitablauf (z.B. 300) ODER im Format MM:SS (zur Zeit z.B. 05:00)
#alert_at_2 = 9:59
alert_at_2 = 600
# Sounddatei für zweiten Alarm mit startoffset (Format: dateiname:start_sekunde)
sound_file_2_1 = sounds/alarm-2.mp3:1

# Erster Zeitwert für Soundalarm als Sekunden vor Zeitablauf (z.B. 300) ODER im Format MM:SS (zur Zeit z.B. 05:00)
alert_at_1 = 1:00
#alert_at_1 = 590
# Sound-Liste für ersten Alarm (Format: dateiname:start_sekunde:fade_sekunden)
# Es wird zufällig einer dieser Sounds gewählt
sound_file_1_1 = sounds/Music/ACDC-All_Night_Long.mp3:17:3
sound_file_1_2 = sounds/Music/ACDC_TNT.mp3:24:3
sound_file_1_3 = sounds/Music/Alan_Walker_-_The_Spectre.mp3:20:3
sound_file_1_4 = sounds/Music/Alvaro_Soler_-_La_Cintura.mp3:18:3
sound_file_1_5 = sounds/Music/moreMusic/02-david_guetta_feat._rihanna_-_._rihanna_-_whos_that_chick_(original_mix)-ume.mp3:4:3
sound_file_1_6 = sounds/Music/Armin_van_Buuren_-_Blah_Blah_Blah.mp3:11:3
sound_file_1_7 = sounds/Music/moreMusic/02_Allein_Allein.mp3:21:3
sound_file_1_8 = sounds/Music/Avicii_-_Levels.mp3:8:3
sound_file_1_9 = sounds/Music/moreMusic/09_-_Westerland.mp3:15:3
sound_file_1_10 = sounds/Music/Axwell__Ingrosso_-_More_Than_You_Know.mp3:0:3
sound_file_1_11 = sounds/Music/moreMusic/102_mando_diao_-_dance_with_somebody.mp3:6:3
sound_file_1_12 = sounds/Music/moreMusic/103_sugababes_-_push_the_button.mp3:0:3
sound_file_1_13 = sounds/Music/Bob_Sinclar_-_Rock_This_Party.mp3:31:3
sound_file_1_14 = sounds/Music/moreMusic/116_bob_sinclar_pres._goleo_vi_feat._gary_nesta_pine_-_love_generation.mp3:14:3
sound_file_1_15 = sounds/Music/moreMusic/209_anastacia_-_sick_and_tired.mp3:5:3
sound_file_1_16 = sounds/Music/Calvin_Harris_-_Giant_.mp3:0:3
sound_file_1_18 = sounds/Music/Coldplay_-_A_Sky_Full_Of_Stars.mp3:33:3
sound_file_1_20 = sounds/Music/Crazy_Town_-_Butterfly.mp3:0:3
sound_file_1_21 = sounds/Music/Cyndi_Lauper_-_Girls_Just_Want_To_Have_Fun_.mp3:15:3
sound_file_1_22 = sounds/Music/Daddy_Yankee__Katy_Perry_feat._Snow_-_Con_Calma_Remix_.mp3:10:3
sound_file_1_23 = sounds/Music/moreMusic/213_peter_fox_-_haus_am_see.mp3:8:3
sound_file_1_24 = sounds/Music/moreMusic/215_culcha_candela_-_hamma.mp3:10:3
sound_file_1_25 = sounds/Music/moreMusic/216_fettes_brot_-_emanuela.mp3:0:3
sound_file_1_26 = sounds/Music/moreMusic/Alligatoah_-_Du_bist_schön_(Official_Video).mp3:18:3
sound_file_1_27 = sounds/Music/Dynoro_Gigi_DAgostino_-_In_My_Mind_.mp3:47:3
sound_file_1_28 = sounds/Music/Dzeko__Torres_-_LAmour_Toujours_featDelaney_Jane_.mp3:62:3
sound_file_1_29 = sounds/Music/moreMusic/BONEZ_MC_&_RAF_CAMORA_feat._MAXWELL_-_Ohne_mein_Team.mp3:20:3
sound_file_1_30 = sounds/Music/moreMusic/Baha_Men_-_Who_Let_The_Dogs_Out.mp3:0
sound_file_1_31 = sounds/Music/EMF_-_Unbelievable_.mp3:6:3
sound_file_1_32 = sounds/Music/Eric_Prydz_–_Call_On_Me_.mp3:15:3
sound_file_1_34 = sounds/Music/Flo_Rida_-_Good_Feeling_.mp3:0:3
sound_file_1_35 = sounds/Music/moreMusic/mickie-krause-schatzi-schenk-mir-ein-foto.mp3:16:3
sound_file_1_38 = sounds/Music/GALA_-_Freed_from_desire_.mp3:8:3
sound_file_1_39 = sounds/Music/Gigi_DAgostino_-_The_Riddle_.mp3:8:3
sound_file_1_42 = sounds/Music/HUGEL_feat._Amber_van_Day_-_WTF_.mp3:8:3
sound_file_1_43 = sounds/Music/moreMusic/David_Guetta_&_Sia-Titanium.mp3:0
sound_file_1_44 = sounds/Music/moreMusic/cascada-evacuate_the_dancefl.mp3:0
sound_file_1_45 = sounds/Music/moreMusic/Flo_Rida-Hangover_Feat._Taio_Cruz.mp3:0
sound_file_1_46 = sounds/Music/moreMusic/markus-becker-das-rote-pferd-feat-mallorca-cowboys.mp3:16:3
sound_file_1_47 = sounds/Music/Justin_Timberlake_-_CANT_STOP_THE_FEELING.mp3:0:3
sound_file_1_48 = sounds/Music/Kings_Of_Leon_-_Sex_on_Fire_.mp3:5:3
sound_file_1_49 = sounds/Music/Kungs_vs_Cookin_on_3_Burners_-_This_Girl_.mp3:0:3
sound_file_1_51 = sounds/Music/Los_Del_Rio_-_Macarena_.mp3:0:3
sound_file_1_52 = sounds/Music/Lost_Frequencies___Zonderling_-_Crazy_.mp3:4:3
sound_file_1_53 = sounds/Music/Loud_Luxury_feat_brando_-_Body_.mp3:9:3
sound_file_1_54 = sounds/Music/Luis_Fonsi__Demi_Lovato_-_Echame_La_Culpa_.mp3:15:3
sound_file_1_55 = sounds/Music/MACKLEMORE___RYAN_LEWIS_-_CANT_HOLD_US_.mp3:80:3
sound_file_1_56 = sounds/Music/Mark_Forster_-_194_Laender_.mp3:0:3
sound_file_1_62 = sounds/Music/Matt_Simons_-_We_Can_Do_Better_.mp3:44:3
sound_file_1_64 = sounds/Music/Metallica_-_Whiskey_In_The_Jar_.mp3:9:3
sound_file_1_65 = sounds/Music/Ofenbach_-_Be_Mine_.mp3:48:3
sound_file_1_66 = sounds/Music/Panic_At_The_Disco_-_High_Hopes_.mp3:11:3
sound_file_1_67 = sounds/Music/Pharrell_Williams_-_Happy_.mp3:4:3
sound_file_1_70 = sounds/Music/Pitbull,_Kesha_-_Timber_.mp3:0:3
sound_file_1_72 = sounds/Music/Rednex_-_Cotton_Eye_Joe_.mp3:0:3
sound_file_1_73 = sounds/Music/Reel_2_Real__-_I_Like_To_Move_It_2010_.mp3:34:3
sound_file_1_74 = sounds/Music/Regard_-_Ride_It_.mp3:26:3
sound_file_1_76 = sounds/Music/Rihanna_-_Dont_Stop_The_Music_.mp3:17:3
sound_file_1_77 = sounds/Music/Rihanna_-_SuM_.mp3:0:3
sound_file_1_79 = sounds/Music/Scooter__-_Maria_.mp3:68:3
sound_file_1_80 = sounds/Music/Seeed_-_Augenbling_.mp3:11:3
sound_file_1_81 = sounds/Music/Sigma_-_Nobody_To_Love_.mp3:40:3
sound_file_1_84 = sounds/Music/Steve_Aoki___MARNIK_-_Bella_Ciao_.mp3:5:3
sound_file_1_86 = sounds/Music/The_Black_Eyed_Peas_-_I_Gotta_Feeling.mp3:0:6
sound_file_1_89 = sounds/Music/The_Offspring_-_Pretty_Fly_.mp3:8:3
sound_file_1_90 = sounds/Music/The_White_Stripes_-_Seven_Nation_Army_.mp3:11:3
sound_file_1_100 = sounds/Music/Was_wollen_wir_trinken_2K17_.mp3:0:3
sound_file_1_95 = sounds/Music/Topic-_Breaking_Me_.mp3:4:3
sound_file_1_97 = sounds/Music/Usher_-_DJ_Got_Us_Fallin_In_Love_.mp3:28:3


# Zweiter Zeitwert für Endealarm (in Sekunden)
ende_alert = 1
# Sounddatei für zweiten Alarm mit startoffset (Format: dateiname:start_sekunde)
    # alarm-1.wav:0     alarm-2.mp3:0
ende_sound = sounds/alarm-1.wav:0
